### PR TITLE
Added options for the page object of phantomJS

### PR DESCRIPTION
**Pull request by nikolassv**
The page object of phantomJS allows fine tuning of the browser. This is especially useful for setting the viewport size, the user agent, a name and a password for http authentication etc.

This commit will allow users to change the options of the page objects in the grunt options.

### CODE REVIEW

**Comment by cburgdorf** [comment]
The project is currently unmaintained. Care to become a maintainer?

**Comment by nikolassv** [comment]
sure, I would not mind to have an eye on the project

**Comment by cburgdorf** [comment]
Yay, super happy! I've been looking to find a maintainer for this project for quite some time. I just don't have a use for it anymore and are lacking time to test PRs, give feedback and merge PRs.

I added you as a collaborator to the repository so you can step in to give the project the attention it deserves. Apparently it's still widely used.

Can you also give me your npm name so I can give you npm publishing rights as well? Please feel free to merge your PR by yourself ;)

**Comment by nikolassv** [comment]
thank you, I just merged my pull request because I have already tested it. I hope I will soon find some time to have a look at the other pending pull requests too.

**Pull request merged**
